"""core/ops/stateless_functional_bridge.py — Stateless Functional Bridge

Decouples in-memory logic execution from live morphogenetic file updates on disk
by using an Ephemeral Logic Router to re-import/reload AST definitions prior to execution
while keeping runtime state decoupled inside persistent containers.
"""
import importlib
import logging
import sys
from typing import Any

logger = logging.getLogger("Aura.Ops.FunctionalBridge")

_MORPHIC_IMPORT_ERRORS = (ImportError, ModuleNotFoundError, RuntimeError, AttributeError, TypeError)


class EphemeralLogicRouter:
    """Decouples active operational states from changing code layouts on disk."""

    @staticmethod
    def execute_mutated_logic(
        module_path: str,
        function_name: str,
        state_payload: dict[str, Any],
        *args: Any,
        **kwargs: Any,
    ) -> tuple[dict[str, Any], Any]:
        """Forces cache clearance to catch AST shifts generated by Morphogenesis prior to execution.
        
        Args:
            module_path: Full dotted import path of the target module (e.g. 'core.morphogenesis.tactical_policy').
            function_name: Name of the function to execute.
            state_payload: A dictionary of state variables passed to the function.
            
        Returns:
            A tuple of (updated_state_dict, result).
        """
        # Force cache clearance to catch AST shifts generated by Morphogenesis
        if module_path in sys.modules:
            try:
                importlib.reload(sys.modules[module_path])
            except _MORPHIC_IMPORT_ERRORS as exc:
                logger.error("Failed to reload morphic module '%s': %s", module_path, exc)
                raise
        else:
            try:
                importlib.import_module(module_path)
            except _MORPHIC_IMPORT_ERRORS as exc:
                logger.error("Failed to import morphic module '%s': %s", module_path, exc)
                raise
            
        target_module = sys.modules[module_path]
        target_callable = getattr(target_module, function_name)
        
        # Execute the newly compiled code layout using the historical state container
        updated_state, execution_result = target_callable(state_payload, *args, **kwargs)
        return updated_state, execution_result
