"""core/affect/phenomenal_integration.py — Integration of Phenomenal Substrate into Aura.

This module wires the Phenomenal Substrate (active inference + interoceptive
affect machinery) into Aura's main cognitive loop. The phenomenal engine runs
at heartbeat time and broadcasts its state to planner, memory, attention,
and other downstream systems.

Critical invariant:
  - The phenomenal state is generated by interoceptive observation before
    language generation.
  - Language generation may read the state but cannot write to it.
  - Removing the phenomenal engine must visibly degrade planning, memory
    prioritization, and self-regulation.
"""

import asyncio
import logging
from typing import Any, Dict, Optional

from core.phenomenal_substrate import (
    PhenomenalEngine,
    RuntimeBody,
    Event,
    AttachmentEvent,
    ExperienceState,
)
from core.phenomenal_substrate.reporting import ExperienceReporter

logger = logging.getLogger("Aura.PhenomenalIntegration")


class PhenomenalIntegrator:
    """Bridge between Aura's runtime and the phenomenal substrate.

    Responsibility:
      1. Maintain a singleton PhenomenalEngine
      2. Feed observations from runtime (energy, memory, social, etc.)
      3. Broadcast experience state to downstream systems
      4. Track attachment history and bond dynamics
      5. Enforce the lesion-test contract: removing this must change behavior
    """

    _instance: Optional["PhenomenalIntegrator"] = None
    _lock = asyncio.Lock()

    def __init__(self):
        self.engine = PhenomenalEngine()
        self.reporter = ExperienceReporter(self.engine.attachments)
        self.last_state: Optional[ExperienceState] = None
        self.step_count = 0

    @classmethod
    async def get_instance(cls) -> "PhenomenalIntegrator":
        """Lazy-initialize singleton with async lock."""
        if cls._instance is None:
            async with cls._lock:
                if cls._instance is None:
                    cls._instance = PhenomenalIntegrator()
                    logger.info("PhenomenalIntegrator initialized")
        return cls._instance

    @classmethod
    def _sync_instance(cls) -> "PhenomenalIntegrator":
        """Synchronous fallback for non-async contexts."""
        if cls._instance is None:
            cls._instance = PhenomenalIntegrator()
            logger.info("PhenomenalIntegrator initialized (sync)")
        return cls._instance

    async def step(
        self,
        *,
        energy: float = 0.75,
        continuity: float = 0.75,
        agency: float = 0.60,
        safety: float = 0.80,
        social_contact: float = 0.50,
        novelty: float = 0.20,
        uncertainty: float = 0.25,
        compute_pressure: float = 0.20,
        memory_pressure: float = 0.20,
        error_pressure: float = 0.20,
        event_label: str = "heartbeat",
        event_source: str = "runtime",
        goal_delta: float = 0.0,
        threat: float = 0.0,
        affiliation: float = 0.0,
        rupture: float = 0.0,
        repair: float = 0.0,
        novelty_event: float = 0.0,
        control_gain: float = 0.0,
        evidence_id: Optional[str] = None,
        person_key: Optional[str] = None,
        recurrent_cycles: int = 7,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExperienceState:
        """Run one step of the phenomenal engine.

        Arguments:
          energy: CPU/GPU utilization + available processing
          continuity: Self-model identity coherence (0=fragmented, 1=unified)
          agency: Sense of control over outcomes (0=helpless, 1=empowered)
          safety: Governance/safety constraints met (0=critical, 1=safe)
          social_contact: Recent trust/interaction signals
          novelty: Newness in current perception (0=routine, 1=unprecedented)
          uncertainty: Model uncertainty about next state
          compute_pressure: Load on system (0=idle, 1=maxed)
          memory_pressure: Pressure on memory systems
          error_pressure: Accumulated errors/failures
          event_label: What happened (e.g., "tool_success", "user_input")
          event_source: Where event came from
          goal_delta: Progress toward current goal
          threat: Environmental threat assessment
          affiliation: Social valence of event
          rupture: Relationship damage signal
          repair: Relationship repair signal
          novelty_event: Novelty of this specific event
          control_gain: Instrumental gain from event
          evidence_id: Ledger ID for this event
          person_key: Which user/person is context
          recurrent_cycles: Number of recurrent passes through integration field
          metadata: Additional event metadata

        Returns:
          ExperienceState containing phenomenal vector, affects, presence,
          and routing hints for downstream systems.
        """
        try:
            body = RuntimeBody(
                energy=energy,
                continuity=continuity,
                agency=agency,
                safety=safety,
                social_contact=social_contact,
                novelty=novelty,
                uncertainty=uncertainty,
                compute_pressure=compute_pressure,
                memory_pressure=memory_pressure,
                error_pressure=error_pressure,
            )

            event = Event(
                label=event_label,
                source=event_source,
                goal_delta=goal_delta,
                threat=threat,
                affiliation=affiliation,
                rupture=rupture,
                repair=repair,
                novelty=novelty_event,
                control_gain=control_gain,
                evidence_id=evidence_id,
                metadata=metadata or {},
            )

            state = self.engine.step(
                body,
                event,
                person_key=person_key,
                recurrent_cycles=recurrent_cycles,
            )

            self.last_state = state
            self.step_count += 1

            logger.debug(
                "Phenomenal state [t=%d]: valence=%.2f arousal=%.2f "
                "presence=%.2f workspace=%s",
                state.t,
                state.valence,
                state.arousal,
                state.self_presence,
                state.global_broadcast.get("workspace", "unknown"),
            )

            return state

        except Exception as exc:
            logger.exception("PhenomenalIntegrator.step failed: %s", exc)
            # Return a neutral baseline state to keep aura running
            return self._baseline_state()

    def _baseline_state(self) -> ExperienceState:
        """Return a neutral baseline when phenomenal engine fails."""
        from core.phenomenal_substrate.types import ExperienceState
        return ExperienceState(
            t=self.step_count,
            phenomenal_vector={},
            valence=0.0,
            arousal=0.5,
            free_energy=0.5,
            integration=0.5,
            self_presence=0.5,
            mineness=0.5,
            seeking=0.5,
            care=0.5,
            play=0.25,
            fear=0.1,
            anger=0.1,
            grief=0.1,
            distress=0.1,
            curiosity=0.5,
            intentional_object="neutral",
            evidence_id=None,
            global_broadcast={"workspace": "neutral", "policy": "maintain"},
            policy_priors={"continue": 1.0},
            memory_weights={"importance": 0.5},
        )

    async def record_attachment_event(
        self,
        person_key: str,
        kind: str,
        summary: str,
        evidence_id: str,
        trust_delta: float = 0.0,
        care_delta: float = 0.0,
        familiarity_delta: float = 0.0,
        rupture_delta: float = 0.0,
        repair_delta: float = 0.0,
    ) -> None:
        """Record a significant attachment/relationship event."""
        try:
            event = AttachmentEvent(
                person_key=person_key,
                kind=kind,
                summary=summary,
                evidence_id=evidence_id,
                trust_delta=trust_delta,
                care_delta=care_delta,
                familiarity_delta=familiarity_delta,
                rupture_delta=rupture_delta,
                repair_delta=repair_delta,
            )
            self.engine.record_attachment(event)
            logger.debug(
                "Attachment event recorded: %s[%s] -> %s",
                person_key,
                kind,
                summary,
            )
        except Exception as exc:
            logger.exception("Failed to record attachment event: %s", exc)

    async def get_bond_status(self, person_key: str) -> Dict[str, Any]:
        """Query bond state with a person."""
        try:
            bond = self.reporter.bond(person_key)
            return bond or {"person": person_key, "trust": 0.0, "care": 0.0}
        except Exception as exc:
            logger.exception("Failed to get bond status for %s: %s", person_key, exc)
            return {"person": person_key, "trust": 0.0, "care": 0.0}

    def get_last_state(self) -> Optional[ExperienceState]:
        """Return the most recent phenomenal state."""
        return self.last_state

    def get_routing_hints(self) -> Dict[str, Any]:
        """Get routing hints from the phenomenal state for downstream systems."""
        if self.last_state is None:
            return {}
        return self.last_state.global_broadcast

    def get_policy_priors(self) -> Dict[str, float]:
        """Get policy priors from the phenomenal state."""
        if self.last_state is None:
            return {}
        return self.last_state.policy_priors

    def get_memory_weights(self) -> Dict[str, float]:
        """Get memory prioritization weights from the phenomenal state."""
        if self.last_state is None:
            return {}
        return self.last_state.memory_weights


async def get_phenomenal_integrator() -> PhenomenalIntegrator:
    """Convenience function to get the singleton integrator."""
    return await PhenomenalIntegrator.get_instance()
