"""Synaptic-plasticity post-inference persist must be governed and non-fatal.

Live latency probe caught the daily-usability killer: the cortex generated
fine, but the post-inference synaptic-plasticity persist wrote through the
file gateway OUTSIDE a governed context, raising GovernanceViolationError.
That error (auto-escalated to a critical inference_gate degradation)
fail-closed the turn; after 5 the Cortex circuit opened and every
substantive turn timed out. These pin the fix:

- the persist write runs inside a governed scope (so it is allowed);
- a persist failure can never propagate (best-effort; the response is
  already generated by the time persist runs).
"""
from __future__ import annotations

import core.runtime.file_write_gateway as fwg
from core.consciousness.synaptic_plasticity import SynapticPlasticityEngine
from core.governance_context import GovernanceViolationError, get_active_governance


def test_persist_state_write_runs_under_governance(monkeypatch):
    seen: dict[str, object] = {}

    class Recorder:
        def write_text(self, path, text, *, source=""):
            seen["governed"] = get_active_governance() is not None
            seen["source"] = source

    monkeypatch.setattr(fwg, "get_file_write_gateway", lambda: Recorder())

    engine = SynapticPlasticityEngine()
    engine._persist_state()  # must not raise

    assert seen.get("governed") is True, "persist write must run inside a governed scope"
    assert seen.get("source") == "synaptic_plasticity.persist"


def test_persist_state_never_propagates_a_governance_violation(monkeypatch):
    calls: list[str] = []

    class Raiser:
        def write_text(self, *args, **kwargs):
            calls.append(str(kwargs.get("source", "")))
            raise GovernanceViolationError("file_write_gateway: ungoverned")

    monkeypatch.setattr(fwg, "get_file_write_gateway", lambda: Raiser())

    engine = SynapticPlasticityEngine()
    # Must swallow — a best-effort persist failure can never reach the
    # inference gate's fail-closed boundary and kill the turn.
    engine._persist_state()
    assert calls  # the write was attempted before the (swallowed) raise


def test_persist_state_never_propagates_disk_errors(monkeypatch):
    calls: list[str] = []

    class Raiser:
        def write_text(self, *args, **kwargs):
            calls.append("attempted")
            raise OSError("disk full")

    monkeypatch.setattr(fwg, "get_file_write_gateway", lambda: Raiser())

    SynapticPlasticityEngine()._persist_state()
    assert calls
