"""A declared histogram nobody writes to reads empty forever.

LIVE, 2026-08-10. Asked "what is your median response latency today, in
milliseconds?", Aura answered:

    "My median response latency today is 152 milliseconds. That's from the time
    I receive a request to the first byte of output being generated by my
    model."

Confident, specific, correctly-united, and invented — nothing in the runtime
timed a chat turn. Looking for what did exist turned up the wider fault:
install_standard_histograms() declared eight histograms, each with a named
owner file, and three of them had no writer anywhere in the tree —

    Aura.Reconcile.DurationMs    owner core/runtime/reconcile.py
    Aura.Admission.DurationMs    owner core/runtime/admission.py
    Aura.Lifecycle.TransitionMs  owner core/runtime/lifecycle.py

An unwritten histogram is worse than an absent one. It appears in
histograms_report() with a name, a unit, an owner and a count of zero, which
reads exactly like a subsystem that is idle rather than one that was never
instrumented. This is the same shape as the half-wired channels of 2026-08-09,
mirrored: there the writers had no reader, here the declarations had no writer.

The three are now wired at their declared owners, and Aura.Chat.TurnMs added
for the quantity that started this. The ratchet is the general property — a
declaration is a promise that a number exists.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
SEARCH_ROOTS = ("core", "interface")

#: Histograms that are legitimately declared by a caller that supplies its own
#: name at runtime, so no literal appears in the tree. Must stay empty unless
#: there is a real case; every entry is a hole in the ratchet.
DYNAMIC_NAME_ALLOWLIST: frozenset[str] = frozenset()


def _declared() -> list[dict]:
    """Every standard histogram's spec, including its declared owner.

    histograms_report() reports owners as a flat list rather than per
    histogram, so the specs are read from the registry itself.
    """
    from core.observability.histograms import (
        get_histogram,
        histograms_report,
        install_standard_histograms,
    )

    install_standard_histograms()
    specs: list[dict] = []
    for name in sorted(histograms_report().get("histograms", {})):
        histogram = get_histogram(name)
        if histogram is not None:
            specs.append(histogram.spec.to_dict())
    return specs


def _python_sources() -> list[Path]:
    files: list[Path] = []
    for root in SEARCH_ROOTS:
        files.extend((REPO / root).rglob("*.py"))
    return [f for f in files if "__pycache__" not in f.parts]


def _writer_sites(name: str) -> list[str]:
    """Files mentioning this histogram name outside the histograms module."""
    pattern = re.compile(rf"""['"]{re.escape(name)}['"]""")
    hits: list[str] = []
    for path in _python_sources():
        if path.name == "histograms.py":
            continue
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        if pattern.search(text):
            hits.append(str(path.relative_to(REPO)))
    return hits


def test_standard_histograms_are_declared() -> None:
    names = {h["name"] for h in _declared()}

    assert "Aura.Chat.TurnMs" in names, "chat turn latency must be measurable"
    assert len(names) >= 9


@pytest.mark.parametrize("spec", _declared(), ids=lambda s: s["name"])
def test_every_declared_histogram_has_a_writer(spec: dict) -> None:
    """The ratchet. A declaration without a writer is a number that never exists."""
    name = spec["name"]
    if name in DYNAMIC_NAME_ALLOWLIST:
        pytest.skip(f"{name} is written under a runtime-composed name")

    writers = _writer_sites(name)

    assert writers, (
        f"{name} is declared (owner {spec.get('owner')!r}) but nothing writes to it. "
        "It will read zero forever, which is indistinguishable from an idle "
        "subsystem. Either record to it or remove the declaration."
    )


@pytest.mark.parametrize("spec", _declared(), ids=lambda s: s["name"])
def test_declared_owner_is_a_real_file(spec: dict) -> None:
    """An owner is who to ask about the number; a stale path answers nobody."""
    owner = str(spec.get("owner") or "").strip()

    assert owner, f"{spec['name']} declares no owner"
    assert (REPO / owner).exists(), f"{spec['name']} owner {owner!r} does not exist"


def test_chat_turn_latency_is_recorded_at_the_user_visible_boundary() -> None:
    """Timing an inner phase would answer a question nobody asked.

    "How long did that take?" means the whole turn, including queueing and
    every phase, which is what api_chat wraps.
    """
    source = (REPO / "interface/routes/chat.py").read_text(errors="replace")
    marker = "async def api_chat("
    body = source[source.find(marker) : source.find(marker) + 4000]

    assert "Aura.Chat.TurnMs" in body
    assert "perf_counter" in body
    # In `finally`, so a slow failure is still counted as waiting.
    assert body.find("finally:") < body.find("Aura.Chat.TurnMs")


@pytest.mark.parametrize(
    ("name", "owner"),
    [
        ("Aura.Reconcile.DurationMs", "core/runtime/reconcile.py"),
        ("Aura.Admission.DurationMs", "core/runtime/admission.py"),
        ("Aura.Lifecycle.TransitionMs", "core/runtime/lifecycle.py"),
    ],
)
def test_the_three_dead_histograms_are_written_by_their_declared_owner(
    name: str, owner: str
) -> None:
    """Not merely written somewhere — written where the declaration says."""
    assert owner in _writer_sites(name)
