"""Legacy governance-lint exports retained for older proof tooling."""

CONSEQUENTIAL_CALLS = (
    "memory_facade.write",
    "memory_facade.add",
    "memory_facade.persist_unsafe",
    "execute_tool",
    "shell_exec",
    "run_shell",
    "post_external",
    "modify_code",
    "fine_tune",
    "self_modify",
    "social_post",
    "structural_mutator.apply_patch",
    "shadow_ast_healer.repair",
    "wallet.execute",
)

ALLOW_LIST = {
    "core/agency/agency_orchestrator.py",
    "core/agency/autonomous_task_engine.py",
    "core/agency/capability_token.py",
    "core/agency/skill_library.py",
    "core/agi/curiosity_daemon.py",
    "core/agi/curiosity_explorer.py",
    "core/autonomy/behavior_controller.py",
    "core/autonomy/proactive_presence.py",
    "core/autonomy/research_cycle.py",
    "core/brain/llm/local_agent_client.py",
    "core/brain/react_loop.py",
    "core/cognitive/state_machine.py",
    "core/collective/delegator.py",
    "core/coordinators/cognitive_coordinator.py",
    "core/coordinators/metabolic_coordinator.py",
    "core/coordinators/tool_executor.py",
    "core/curiosity_engine.py",
    "core/embodiment/world_bridge.py",
    "core/executive/authority_gateway.py",
    "core/kernel/upgrades_10x.py",
    "core/orchestrator/main.py",
    "core/orchestrator/mixins/autonomy.py",
    "core/orchestrator/mixins/incoming_logic.py",
    "core/orchestrator/mixins/message_pipeline.py",
    "core/orchestrator/mixins/response_processing.py",
    "core/orchestrator/mixins/tool_execution.py",
    "core/phases/response_generation_unitary.py",
    "core/self_modification/safe_pipeline.py",
    "core/self_modification/self_modification_engine.py",
    "core/self_modification/shadow_ast_healer.py",
    "core/self_modification/structural_mutator.py",
    "core/soul.py",
    "core/sovereignty/migration.py",
    "core/sovereignty/wallet.py",
    "core/will.py",
    "interface/routes/system.py",
}

__all__ = ["ALLOW_LIST", "CONSEQUENTIAL_CALLS"]
